models/WorkPlaceReservation.php
<?php

namespace app\models;

use Yii;
use yii\db\Query;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "work_place_reservation".
 *
 * @property int $id
 * @property int $work_place_id
 * @property int $employee_id
 * @property string $reservation_date_start
 * @property string $reservation_date_end
 * @property int|null $created_at
 * @property int|null $updated_at
 *
 * @property Employee $employee
 * @property WorkPlace $workPlace
 */
class WorkPlaceReservation extends \yii\db\ActiveRecord
{
    // public function beforeSave($insert)
    // {
    //     if( ! parent::beforeSave($insert)) {
    //         return false;
    //     }

    //     $this->reservation_date_start = strtotime($this->reservation_date_start);
    //     $this->reservation_date_end = strtotime($this->reservation_date_end);
        
    //     return true;
    // }
    
    public function behaviors()
    {
        return [
            'class' => TimestampBehavior::className(),
        ];
    }
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'work_place_reservation';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['work_place_id', 'employee_id', 'reservation_date_start', 'reservation_date_end'], 'required'],
            [['work_place_id', 'employee_id', 'created_at', 'updated_at'], 'integer'],
            [['reservation_date_start', 'reservation_date_end'], 'safe'],
            [['employee_id'], 'exist', 'skipOnError' => true, 'targetClass' => Employee::className(), 'targetAttribute' => ['employee_id' => 'id']],
            [['work_place_id'], 'exist', 'skipOnError' => true, 'targetClass' => WorkPlace::className(), 'targetAttribute' => ['work_place_id' => 'id']],
            ['reservation_date_end', 'validateReservationDate'],
            ['reservation_date_end', 'validateReservationEndBeforeReservationStart'],
        ];
    }

    public function validateReservationEndBeforeReservationStart($attribute, $params)
    {
        if($this->reservation_date_start >= $this->reservation_date_end) {
            $this->addError('reservation_date_end', 'Koniec rezerwacji nie może upłynąć przed jej rozpoczęciem!');
        }
    }

    public function validateReservationDate($attribute, $params)
    {
        $startTime = $this->reservation_date_start;
        $endTime = $this->reservation_date_end;

        $expression = new Expression("reservation_date_start < '{$startTime}' AND reservation_date_end > '{$startTime}' AND work_place_id = {$this->work_place_id}");
        $expression2 = new Expression("reservation_date_start < '{$endTime}' AND reservation_date_end > '{$endTime}' AND work_place_id = {$this->work_place_id}");
        $expression3 = new Expression("reservation_date_start > '{$startTime}' AND reservation_date_end < '{$endTime}' AND work_place_id = {$this->work_place_id}");
        $result = (new Query())
                        ->select('*')
                        ->from('work_place_reservation')
                        ->where($expression)
                        ->orWhere($expression2)
                        ->orWhere($expression3)
                        ->all();

        $count = count($result);

        if($count > 0) {
            $this->addError('reservation_date_start', "Istnieje już rezerwacja w tym przedziale czasowym");
            $this->addError('reservation_date_end', "Istnieje już rezerwacja w tym przedziale czasowym"); 
        }
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'work_place_id' => 'ID Miejsca pracy',
            'employee_id' => 'ID Pracownika',
            'reservation_date_start' => 'Start rezerwacji',
            'reservation_date_end' => 'Koniec rezerwacji',
            'created_at' => 'Utworzono',
            'updated_at' => 'Zaktualizowano',
        ];
    }

    /**
     * Gets query for [[Employee]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getEmployee()
    {
        return $this->hasOne(Employee::className(), ['id' => 'employee_id']);
    }

    /**
     * Gets query for [[WorkPlace]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getWorkPlace()
    {
        return $this->hasOne(WorkPlace::className(), ['id' => 'work_place_id']);
    }
}

controllers/WorkPlaceController.php
<?php

namespace app\controllers;

use Yii;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\web\Response;
use app\models\WorkPlace;
use app\models\WorkPlaceSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * WorkPlaceController implements the CRUD actions for WorkPlace model.
 */
class WorkPlaceController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all WorkPlace models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new WorkPlaceSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->renderAjax('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new WorkPlace model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new WorkPlace();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $model->save();
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    public function actionValidate()
    {
        $model = new WorkPlace();

        if ( ! Yii::$app->request->isAjax) return;
        
        if ($model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
    /**
     * Updates an existing WorkPlace model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $model->save();
        }

        return $this->renderAjax('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing WorkPlace model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
    }

    /**
     * Finds the WorkPlace model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return WorkPlace the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = WorkPlace::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionFetchWorkPlaceEquipmentById(int $workPlaceId)
    {
        $model = $this->findModel($workPlaceId);

        $workPlaceEquipment = $model->getWorkPlaceEquipments()->all();

        $workPlaceEquipment = ArrayHelper::toArray($workPlaceEquipment, [
            'app\models\WorkPlaceEquipment' => [
                'id',
                'equipmentFullDescription',
        ]]);
        
        return json_encode($workPlaceEquipment);
    }
}

controllers/WorkPlaceReservationController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Response;
use yii\widgets\ActiveForm;
use app\models\WorkPlaceReservation;
use app\models\WorkPlaceReservationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * WorkPlaceReservationController implements the CRUD actions for WorkPlaceReservation model.
 */
class WorkPlaceReservationController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all WorkPlaceReservation models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new WorkPlaceReservationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if(Yii::$app->request->isAjax) {
            return $this->renderAjax('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new WorkPlaceReservation model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new WorkPlaceReservation();

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $model->save();
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    public function actionValidate()
    {
        $model = new WorkPlaceReservation();

        if ( ! Yii::$app->request->isAjax) return;
        
        if ($model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }

    /**
     * Updates an existing WorkPlaceReservation model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return $model->save();
        }

        return $this->renderAjax('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing WorkPlaceReservation model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
    }

    /**
     * Finds the WorkPlaceReservation model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return WorkPlaceReservation the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = WorkPlaceReservation::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/work-place-reservation/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

use app\models\WorkPlace;
use app\models\Employee;
use yii\helpers\ArrayHelper;
use kartik\datetime\DateTimePicker;
use richardfan\widget\JSRegister;
use app\assets\FormAsset;

FormAsset::register($this);
/* @var $this yii\web\View */
/* @var $model app\models\WorkPlaceReservation */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="work-place-reservation-form">

    <?php $form = ActiveForm::begin([
        'id' => 'work-place-reservation-activeform',
        'enableAjaxValidation' => true,
        'action' => ['work-place-reservation/create'],
        'validationUrl' => '/work-place-reservation/validate',
        'options' => ['class' => 'active-form'],
    ]); ?>

    <?= $form->field($model, 'work_place_id')
                                    ->dropDownList(ArrayHelper::map(WorkPlace::find()->asArray()->all(), 'id', 'name'), [
                                        'id' => 'work-place-id-dropdown',
                                    ])
                                    ->label('Miejsce pracy'); ?>

    <?php
        echo Html::label('Wyposażenie', 'work-place-equipment-textarea', ['class' => 'control-label']);
        echo Html::textarea('work-place-equipment-textarea', '', [
            'class' => 'form-control', 'rows' => 5, 'id' => 'work-place-equipment-textarea', 'readonly' => true,
            ]);
    ?>

    <?= $form->field($model, 'employee_id')
                                    ->dropDownList(ArrayHelper::map(Employee::find()->all(), 'id', 'fullName'))
                                    ->label('Rezerwujący'); ?>

    <?= $form->field($model, 'reservation_date_start')->widget(DateTimePicker::classname(), [
        'options' => ['placeholder' => 'Start rezerwacji...'],
        'pluginOptions' => ['autoclose' => true],
    ]); ?>
    
    <?= $form->field($model, 'reservation_date_end')->widget(DateTimePicker::classname(), [
        'options' => ['placeholder' => 'Koniec rezerwacji...'],
        'pluginOptions' => ['autoclose' => true],
    ]); ?>

    <div class="form-group">
        <?= Html::submitButton('Zapisz', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php JSRegister::begin(); ?>
<script>
    $(document).ready(function() {
        var workPlaceIdDropdown = $('#work-place-id-dropdown');
        var workPlaceEquipmentTextArea = $('#work-place-equipment-textarea');

        workPlaceIdDropdown.on('change', function() {
            fetchWorkplaceEquipmentById(workPlaceIdDropdown.val());
        });
        
        fetchWorkplaceEquipmentById(workPlaceIdDropdown.val());
        
        function fetchWorkplaceEquipmentById(workPlaceId) {
            $.ajax({
                url: '/work-place/fetch-work-place-equipment-by-id',
                type: 'GET',
                data: { workPlaceId: workPlaceId },
            })
            .done(function(response) {
                let formatResponse = JSON.parse(response);
                updateWorkPlaceEquipmentTextArea(formatResponse);
            });
        }

        function updateWorkPlaceEquipmentTextArea(workPlaceEquipment)
        {
            workPlaceEquipmentTextArea.text('');
            
            for(var item of workPlaceEquipment)
            {
                workPlaceEquipmentTextArea.append(`${item.equipmentFullDescription}\n`);
            }
        }
    });
</script>
<?php JSRegister::end(); ?>

views/work-place-reservation/_master-search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\WorkPlaceSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="work-place-search master-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'master_search')->textInput(['placeholder' => 'Szukaj...'])->label(false) ?>

    <div class="form-group">
        <?php //echo Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?php //echo Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/work-place-reservation/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\WorkPlaceReservation */

$this->title = 'Utwórz rezerwacje';
$this->params['breadcrumbs'][] = ['label' => 'Rezerwacje', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-place-reservation-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/work-place-reservation/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\assets\ActionButtonsAsset;

ActionButtonsAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel app\models\WorkPlaceReservationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Lista rezerwacji';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="work-place-reservation-index index-container" data-controller="work-place-reservation">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="before-table-container">
        <?= Html::button('Utwórz', ['class' => 'btn btn-success create-button']) ?>
        <?php //echo $this->render('_master-search', ['model' => $searchModel]); ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'workPlaceName',
                'label' => 'Nazwa miejsca pracy',
                'value' => function($model, $key, $index) {
                    return $model->workPlace->name ?? '-';
                },
            ],
            [
                'attribute' => 'employeeName',
                'label' => 'Rezerwujący',
                'value' => function($model, $key, $index) {
                    return $model->employee->fullName ?? '-';
                },
            ],
            'reservation_date_start',
            'reservation_date_end',
            // 'work_place_id',
            // 'employee_id',
            // 'created_at',
            //'updated_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete}',
                'buttons' => [
                    'update' => function($url, $model, $key) {
                        return Html::button('Aktualizuj', ['class' => 'btn btn-primary btn-sm update-button', 'data-record-id' => $key]);
                    },
                    'delete' => function($url, $model, $key) {
                        return Html::button('Usuń', ['class' => 'btn btn-danger btn-sm delete-button', 'data-record-id' => $key]);
                    }
                ],
            ],
        ],
    ]); ?>
</div>

views/work-place-reservation/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\WorkPlaceReservation */

$this->title = 'Aktualizuj Rezerwacje: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Rezerwacje', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Aktualizuj';
?>
<div class="work-place-reservation-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>